# Docker Compose with secrets management
# Usage: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up

version: '3.8'

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  mongodb_password:
    file: ./secrets/mongodb_password.txt
  github_token:
    file: ./secrets/github_token.txt
  wandb_api_key:
    file: ./secrets/wandb_api_key.txt
  hf_token:
    file: ./secrets/hf_token.txt

services:
  postgres:
    secrets:
      - postgres_password
      - postgres_user
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      # Remove plain text passwords
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=

  mongodb:
    secrets:
      - mongodb_password
    environment:
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_password
      # Remove plain text password
      - MONGO_INITDB_ROOT_PASSWORD=

  downloader:
    secrets:
      - postgres_password
      - postgres_user
      - github_token
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - GITHUB_TOKEN_FILE=/run/secrets/github_token
      # Remove plain text values
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - GITHUB_TOKEN=

  processor:
    secrets:
      - postgres_password
      - postgres_user
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user

  metrics-exporter:
    secrets:
      - postgres_password
      - postgres_user
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user

  trainer:
    secrets:
      - postgres_password
      - postgres_user
      - wandb_api_key
      - hf_token
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - WANDB_API_KEY_FILE=/run/secrets/wandb_api_key
      - HF_TOKEN_FILE=/run/secrets/hf_token
      # Remove plain text values
      - HF_TOKEN=
      - WANDB_API_KEY=
