apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-config
  namespace: codelupe
data:
  DATABASE_URL: "postgres://coding_user:coding_pass@postgres:5432/coding_db?sslmode=disable"
  REPOS_DIR: "/app/repos"
  GOMAXPROCS: "24"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: codelupe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:16-alpine
        command: ['sh', '-c', 'until pg_isready -h postgres -p 5432 -U coding_user; do echo waiting for postgres; sleep 2; done;']
        env:
        - name: PGPASSWORD
          value: coding_pass
      containers:
      - name: processor
        image: codelupe-processor:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: processor-config
        volumeMounts:
        - name: repos-storage
          mountPath: /app/repos
        - name: logs-storage
          mountPath: /app/logs
        resources:
          requests:
            memory: "8Gi"
            cpu: "12000m"
          limits:
            memory: "16Gi"
            cpu: "24000m"
      volumes:
      - name: repos-storage
        persistentVolumeClaim:
          claimName: repos-pvc
      - name: logs-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: processor
  namespace: codelupe
spec:
  selector:
    app: processor
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP