apiVersion: v1
kind: PersistentVolume
metadata:
  name: repos-pv
  namespace: codelupe
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /host_mnt/g/repos  # Docker Desktop Windows path mapping
    type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-pv
  namespace: codelupe
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/codelupe-models
    type: DirectoryOrCreate

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer